version: 0.1
#
# eb_codebuild_settings:
#   CodeBuildServiceRole: arn:aws:iam::062773471215:role/service-role/codebuild-oneroost-service-role
#   ComputeType: BUILD_GENERAL1_SMALL
#   Image: aws/codebuild/eb-nodejs-4.4.6-amazonlinux-64:2.1.3
#   Timeout: 30

phases:
  install:
    commands:
    #   - echo putting CODEBUILD_BUILD_ID=$CODEBUILD_BUILD_ID into file
    #   - echo "export const build_id = \"$CODEBUILD_BUILD_ID\"" > codebuild_build.js
      - echo "NODE_ENV = $NODE_ENV"
    #   - echo putting pipeline info into file
    #   - aws codepipeline --region us-east-1 get-pipeline-state --name $PIPELINE --output json > pipeline.json
    #   - cat pipeline.json
      - echo Installing gulp...
      - npm install -g gulp@3.9.1
      - echo Installing Yarn...
      - npm install -g yarn@1.0.0
      - echo yarn version && yarn -v
      - echo Installing source Yarn dependencies...
    #   - npm install -g node-sass
      - which gulp && gulp -v
      - yarn --production=false
    #   - yarn global add webpack
    #   - yarn global add babel-loader
    #   - yarn global add babel-preset-react
    #   - yarn global add babel-preset-es2015
    #   - yarn global add babel-preset-stage-3
    #   - webpack -v
    #   - echo installing jest...
    #   - yarn global add jest
    #   - pwd
    #   - echo install sentry-cli
    #   - curl -sL https://sentry.io/get-cli/ | bash
    #   - echo checking sentry installed correctly at
    #   - which sentry-cli
  pre_build:
    commands:
    #   - echo log into sentry with auth token
    #   - sentry-cli info
  build:
    commands:
      - echo Build started on `date`
      - echo starting the gulp build process
      - echo where am I?
      - pwd && ls
    #   - gulp version
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - ls dist
      - ls node
artifacts:
  files:
    - .ebextensions/**/*
    - .elasticbeanstalk/**/*
    - buildspec.yml
    - main.js
    - node/dist/**/*
    - dist/**/*
    - package.json
    - images/**/*
    - yarn.lock
