branch-defaults:
  master:
    environment: staging
global:
  application_name: Oneroost Slack
  default_ec2_keyname: oneroost-aws-eb
  default_platform: Node.js
  default_region: us-east-1
  profile: oneroost
  sc: git
 
