branch-defaults:
  master:
    environment: stage
global:
  application_name: Oneroost Slack
  default_ec2_keyname: poulin_rsa
  default_platform: 64bit Amazon Linux 2017.03 v4.2.2 running Node.js
  default_region: us-east-1
  profile: null
  sc: git
