export const SLACK_CHANNEL_CLASSNAME = 'SlackChannel'
export const SLACK_TEAM_CLASSNAME = 'SlackTeam'
export const USER_CLASSNAME = '_User'
export const INBOUND_CLASSNAME = 'Inbound'
export const VENDOR_CLASSNAME = 'Vendor'
export const REDIRECT_CLASSNAME = 'Redirect'
