export const LOG_IN_REQUEST = "oneroost/user/LOG_IN_REQUEST"
export const LOG_IN_SUCCESS = "oneroost/user/LOGIN_IN_SUCCESS"
export const LOG_IN_ERROR = "oneroost/user/LOG_IN_ERROR"
export const LOG_OUT_REQUEST = "oneroost/user/LOG_OUT_REQUEST"
export const LOG_OUT_SUCCESS = "oneroost/user/LOG_OUT_SUCCESS"
export const UPDATE_USER_INFO = "oneroost/user/UPDATE_USER_INFO"
export const GOOGLE_LOG_IN_SUCCESS = "oneroost/user/GOOGLE_LOG_IN_SUCCESS"
export const GOOGLE_LOG_OUT_SUCCESS = "oneroost/user/GOOGLE_LOG_OUT_SUCCESS"
export const SET_PROVIDER_ERROR = "oneroost/user/SET_PROVIDER_ERROR"

// ALIASES
export const LOG_IN_ALIAS = "oneroost/user/LOG_IN_ALIAS"
export const LOG_OUT_ALIAS = "oneroost/user/LOG_OUT_ALIAS"
export const LOG_IN_GOOGLE_ALIAS = "oneroost/user/LOG_IN_GOOGLE_ALIAS"
export const LOG_OUT_GOOGLE_ALIAS = "oneroost/user/LOG_OUT_GOOGLE_ALIAS"
