EnvironmentConfigurationMetadata:
  Description: Configuration created from the EB CLI using "eb config save".
  DateCreated: '1488865829000'
  DateModified: '1488865829000'
Platform:
  PlatformArn: arn:aws:elasticbeanstalk:us-east-1::platform/Node.js running on 64bit Amazon Linux/3.3.1
OptionSettings:
  aws:elasticbeanstalk:sns:topics:
    Notification Endpoint: alerts@oneroost.com
  aws:elasticbeanstalk:application:environment:
    PARSE_APP_ID: lSNtmvBTimEY6VfOo5zvvOQkljcHeDIOQcjefNUu
    DATABASE_URL: mongodb://oneroost:oneroost@ds147137-a0.mlab.com:47137,ds147137-a1.mlab.com:47137/oneroost-db-0?replicaSet=rs-ds147137
    STRIPE_SECRET_KEY: sk_live_CAgA9ffxAdbwF3H0CQ5D9NuF
    HOSTNAME: https://www.oneroost.com
    PARSE_SERVER_URL: http://localhost
    STRIPE_PUBLISH_KEY: pk_live_1UTmcArmRZQf2g41EoZP0nIq
    PARSE_PORT: '8081'
    ENV_NAME: prod-green
    PARSE_MOUNT: /parse
    NODE_ENV: production
    GA_TRACKING_ID: UA-87950724-1
    PARSE_MASTER_KEY: LqJHvr4fr6kD43RwCawwwq1AxaiGcQpGHZRvpmc9
  aws:elasticbeanstalk:environment:
    ServiceRole: aws-elasticbeanstalk-service-role
    EnvironmentType: LoadBalanced
  aws:elasticbeanstalk:healthreporting:system:
    SystemType: enhanced
  aws:autoscaling:launchconfiguration:
    SecurityGroups:
    - oneroost-eb-sg
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
    InstanceType: t2.micro
    EC2KeyName: poulin_rsa
  aws:elasticbeanstalk:xray:
    XRayEnabled: true
EnvironmentTier:
  Type: Standard
  Name: WebServer
AWSConfigurationTemplateVersion: 1.1.0.0
